# basic options
title: NordLend - 
author: PWRMind
email: your-email@domain.com
description: Компания «Норд-Ленд» осуществляет полный комплекс работ в сфере торгового, теплового и холодильного оборудования
keywords: холодильные шкафы, холодильные машины, холодильные компрессоры, холодильные камеры, торговые стеллажи, стеллажи для магазина, морозильный ларь, холодильное оборудование, холодильная камера для цветов, торговые витрины, промышленное холодильное оборудование, оборудование торговое, холодильный агрегат, Инструмент для холодильщика, Компрессорно-конденсаторные блоки(ККБ), Пила для мяса, стол из нержавейки, Мясорубка, Воздухоохладители, Сплит-система
lang: ru

# Build settings
markdown: kramdown
#permalink: pretty
# theme: minima
collections:
  books:
    output: true
    permalink: /:categories/:title